common: &default_settings
  license_key: 10ea87f88ca03f22220bf13dd3614950a96cb9ae
  app_name: Linkastor
  log_level: info

development:
  <<: *default_settings
  app_name: Linkastor dev
  developer_mode: true
test:
  <<: *default_settings
  monitor_mode: false

production:
  <<: *default_settings